export const SET_TOKEN = "SET_TOKEN";

export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_MAIN_VIEW = 'UPDATE_MAIN_VIEW';
export const UPDATE_BROWSE_VIEW = 'UPDATE_BROWSE_VIEW';

export const FETCH_BROWSE_CATEGORIES = 'FETCH_BROWSE_CATEGORIES';

export const FETCH_CATEGORY_PLAYLIST = 'FETCH_CATEGORY_PLAYLIST';
export const FETCH_FEATURED_PLAYLIST = 'FETCH_FEATURED_PLAYLIST';
export const FETCH_NEW_RELEASES_PLAYLIST = 'FETCH_NEW_RELEASES_PLAYLIST';

export const FETCH_PLAYLIST_TRACKS = 'FETCH_PLAYLIST_TRACKS';
export const FETCH_ALBUM_TRACKS = 'FETCH_ALBUM_TRACKS';
export const FETCH_RECENTLY_PLAYED_TRACKS = 'FETCH_RECENTLY_PLAYED_TRACKS';

export const FETCH_USER_ALBUMS = 'FETCH_USER_ALBUMS';
export const FETCH_USER_TRACKS = 'FETCH_USER_TRACKS';