export const SET_TOKEN = "SET_TOKEN";

export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_SONG_LIST_VIEW = 'UPDATE_SONG_LIST_VIEW';
export const UPDATE_MAIN_VIEW = 'UPDATE_MAIN_VIEW';
export const UPDATE_BROWSE_VIEW = 'UPDATE_BROWSE_VIEW';

export const FETCH_BROWSE_CATEGORIES = 'FETCH_BROWSE_CATEGORIES';

export const FETCH_CATEGORY_PLAYLIST = 'FETCH_CATEGORY_PLAYLIST';
export const FETCH_FEATURED_PLAYLIST = 'FETCH_FEATURED_PLAYLIST';
export const FETCH_NEW_RELEASES_PLAYLIST = 'FETCH_NEW_RELEASES_PLAYLIST';

export const FETCH_PLAYLIST_TRACKS = 'FETCH_PLAYLIST_TRACKS';
export const FETCH_ALBUM_TRACKS = 'FETCH_ALBUM_TRACKS';
export const FETCH_ARTISTS = 'FETCH_ARTISTS';
export const FETCH_ARTIST_TRACKS = 'FETCH_ARTISTS_TRACK';
export const FETCH_RECENTLY_PLAYED_TRACKS = 'FETCH_RECENTLY_PLAYED_TRACKS';

export const FETCH_USER_ALBUMS = 'FETCH_USER_ALBUMS';
export const FETCH_USER_TRACKS = 'FETCH_USER_TRACKS';
export const FETCH_USER_PLAYLISTS = 'FETCH_USER_PLAYLISTS';
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';

export const SET_PLAYER_TRACK = 'SET_PLAYER_TRACK';
export const SET_ALBUM_IMAGE = 'SET_ALBUM_IMAGE';

export const PLAY_TRACK = 'PLAY_TRACK';
export const PAUSE_TRACK = 'PAUSE_TRACK';
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
export const SET_VOLUME = 'SET_VOLUME';

