export const SET_TOKEN = "SET_TOKEN";

export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_MAIN_VIEW = 'UPDATE_MAIN_VIEW';

export const UPDATE_BROWSE_VIEW = 'UPDATE_BROWSE_VIEW';
export const FETCH_BROWSE_CATEGORIES = 'FETCH_BROWSE_CATEGORIES';
export const FETCH_CATEGORIES_PLAYLIST = 'FETCH_CATEGORIES_PLAYLIST';
export const FETCH_FEATURED_PLAYLIST = 'FETCH_FEATURED_PLAYLIST';